<a href="https://colab.research.google.com/github/patelomniraj/ML-Projects/blob/NLP/TF_IDF_on_SMS_Spam_Collection_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import nltk
import re
import pandas as pd
import numpy as np
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [2]:
from nltk.corpus import stopwords

In [10]:
from nltk.stem import PorterStemmer,WordNetLemmatizer
porter = PorterStemmer()
lemma = WordNetLemmatizer()

In [4]:
df = pd.read_csv("/content/SMSSpamCollection.txt",sep='\t',names=['Label','Message']) # converting text file into .CSV

In [5]:
df.head()

,Label,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [25]:
corpus = []

for i in range(0,len(df)):

  # Step 1 Cleanning
  clean_text = re.sub('[^a-zA-Z]',' ',df['Message'][i])

  # Step 2 : Convert string into Words
  words = clean_text.split()

  # Step 3 : Remove StopWords and Apply Lemmatization
  clean_word_list = [lemma.lemmatize(word) for word in words if word not in stopwords.words('english')]

  # Step 4 : Join Words into Sentence
  clean_sentence = ' '.join(clean_word_list)

  corpus.append(clean_sentence)

In [29]:
print(corpus)

['Go jurong point crazy Available bugis n great world la e buffet Cine got amore wat', 'Ok lar Joking wif u oni', 'Free entry wkly comp win FA Cup final tkts st May Text FA receive entry question std txt rate T C apply', 'U dun say early hor U c already say', 'Nah I think go usf life around though', 'FreeMsg Hey darling week word back I like fun still Tb ok XxX std chgs send rcv', 'Even brother like speak They treat like aid patent', 'As per request Melle Melle Oru Minnaminunginte Nurungu Vettam set callertune Callers Press copy friend Callertune', 'WINNER As valued network customer selected receivea prize reward To claim call Claim code KL Valid hour', 'Had mobile month U R entitled Update latest colour mobile camera Free Call The Mobile Update Co FREE', 'I gonna home soon want talk stuff anymore tonight k I cried enough today', 'SIX chance win CASH From pound txt CSH send Cost p day day TsandCs apply Reply HL info', 'URGENT You week FREE membership Prize Jackpot Txt word CLAIM No T C

# TF - IDF (Term Frequency - Inverse Document Frequency)

In [41]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [22]:
tdidf_model = TfidfVectorizer(max_features=100,ngram_range=(1,1),lowercase=True)

In [30]:
y = tdidf_model.fit_transform(corpus).toarray()

In [31]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

Display All Probablity of Important Words

In [35]:
np.set_printoptions(
    edgeitems = 30,
    linewidth = 100000,
    formatter = dict(float=lambda x: "%.4g" % x))

In [36]:
y

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.4342, 0, 0, 0.4612, 0.544, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5503, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.456, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0.4726, 0, 0, 0, 0, 0, 0, 0, 0, 0.4915, 0, 0, 0, 0, 0, 0, 0, 0, 0.572, 0, 0, 0, 0, 0],
       [0.4649, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.4853, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.5745, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

# TF - IDF with N-gram

In [46]:
model = TfidfVectorizer(max_features=100,ngram_range=(2,2),lowercase=True)   # Change ngram range --> Uni (1,1) | Bi (2,2) | Tri (3,3) | Uni-Bi-Tri (1,3)

In [47]:
y = model.fit_transform(corpus).toarray()

In [48]:
np.set_printoptions(
    edgeitems = 30,
    linewidth = 100000,
    formatter = dict(float=lambda x: "%.4g" % x))

In [49]:
y

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [45]:
model.vocabulary_

{'free entry': np.int64(30),
 'to claim': np.int64(81),
 'claim call': np.int64(15),
 'call claim': np.int64(3),
 'free call': np.int64(29),
 'chance win': np.int64(14),
 'txt word': np.int64(85),
 'let know': np.int64(52),
 'please call': np.int64(64),
 'lt gt': np.int64(56),
 'want go': np.int64(93),
 'like lt': np.int64(53),
 'sorry call': np.int64(75),
 'call later': np.int64(8),
 'ur awarded': np.int64(86),
 'how much': np.int64(47),
 'hi hi': np.int64(44),
 'call customer': np.int64(4),
 'customer service': np.int64(22),
 'cash prize': np.int64(13),
 'po box': np.int64(66),
 'we trying': np.int64(95),
 'trying contact': np.int64(82),
 'draw show': np.int64(27),
 'show prize': np.int64(74),
 'prize guaranteed': np.int64(69),
 'guaranteed call': np.int64(38),
 'valid hr': np.int64(91),
 'selected receive': np.int64(71),
 'private your': np.int64(68),
 'your account': np.int64(98),
 'account statement': np.int64(0),
 'statement show': np.int64(76),
 'call identifier': np.int64(5),
 